apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: notes-network-policy
spec:
  podSelector:
    matchLabels:
      app: notes
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: front
    ports:
    - protocol: TCP
      port: 8080