apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zagani212/microservices-gitops.git
    targetRevision: HEAD
    path: environements/prod

  destination: 
    name: in-cluster
    namespace: prod

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true