apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: read-only-role
rules:
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["view"]
- apiGroups: [""]
  resources: ["*"]
  verbs: ["list"]
